# Generated by Django 4.0.6 on 2023-01-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prenomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_de_costos', models.CharField(max_length=100)),
                ('nombre_del_centro_de_costos', models.CharField(max_length=100)),
                ('empleado', models.CharField(max_length=100)),
                ('nombre_del_empleado', models.CharField(max_length=200)),
                ('turno', models.CharField(max_length=100)),
                ('descripción_del_turno', models.CharField(max_length=200)),
                ('concepto', models.CharField(max_length=100)),
                ('nombre_del_concepto', models.CharField(max_length=200)),
                ('vinculación', models.CharField(max_length=100)),
                ('préstamo', models.CharField(max_length=100)),
                ('salario_básico_hora', models.CharField(max_length=100)),
                ('tiempo', models.CharField(max_length=200)),
                ('valor', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'prenomina',
                'verbose_name_plural': 'prenomina',
                'db_table': 'prenomina',
                'order_with_respect_to': 'empleado',
            },
        ),
    ]
