# Generated by Django 4.0.6 on 2023-01-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominametro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenomina',
            name='centro_de_costos',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='prenomina',
            name='concepto',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='prenomina',
            name='descripción_del_turno',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='prenomina',
            name='empleado',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='prenomina',
            name='nombre_del_centro_de_costos',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='prenomina',
            name='nombre_del_concepto',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='prenomina',
            name='nombre_del_empleado',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='prenomina',
            name='préstamo',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='prenomina',
            name='salario_básico_hora',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='prenomina',
            name='tiempo',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='prenomina',
            name='turno',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='prenomina',
            name='valor',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='prenomina',
            name='vinculación',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
