# Generated by Django 4.0.6 on 2023-01-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominametro', '0002_alter_prenomina_centro_de_costos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(default='-', max_length=200)),
                ('nombre', models.CharField(default='-', max_length=200)),
                ('apellido', models.CharField(default='-', max_length=200)),
                ('codigo', models.CharField(default='-', max_length=200)),
                ('cargo', models.CharField(default='-', max_length=200)),
                ('salario_mensual_basico', models.CharField(default='-', max_length=200)),
                ('valor_hora_ordin', models.CharField(default='-', max_length=200)),
                ('periodo_fecha_inicial', models.CharField(default='-', max_length=200)),
                ('periodo_fecha_final', models.CharField(default='-', max_length=200)),
                ('horas_ordinarias', models.CharField(default='-', max_length=200)),
                ('on_0_35', models.CharField(default='-', max_length=200)),
                ('ed_1_25', models.CharField(default='-', max_length=200)),
                ('en_1_75', models.CharField(default='-', max_length=200)),
                ('fd_0_75', models.CharField(default='-', max_length=200)),
                ('fn_1_1', models.CharField(default='-', max_length=200)),
                ('efd_2', models.CharField(default='-', max_length=200)),
                ('efn_2_5', models.CharField(default='-', max_length=200)),
                ('d_o_f_d_1_75', models.CharField(default='-', max_length=200)),
                ('d_o_f_n_2_1', models.CharField(default='-', max_length=200)),
                ('ausencias_remuneradas_hora', models.CharField(default='-', max_length=200)),
                ('ausencias_no_remuneradas_hora', models.CharField(default='-', max_length=200)),
                ('incapacidad_por_enfermedad_general_horas', models.CharField(default='-', max_length=200)),
                ('vr_auxilio_transporte_o_auxilio_de_conectividad', models.CharField(default='-', max_length=200)),
                ('otros_ingresos_no_prestacionales', models.CharField(default='-', max_length=200)),
                ('otros_ingresos_prestacionales', models.CharField(default='-', max_length=200)),
                ('total_devengado', models.CharField(default='-', max_length=200)),
                ('deducción_retención_en_la_fuente', models.CharField(default='-', max_length=200)),
                ('otras_deducciones', models.CharField(default='-', max_length=200)),
                ('deducciones_sgss', models.CharField(default='-', max_length=200)),
                ('neto_a_pagar', models.CharField(default='-', max_length=200)),
            ],
            options={
                'verbose_name': 'plantilla',
                'verbose_name_plural': 'plantilla',
                'db_table': 'plantilla',
                'order_with_respect_to': 'nombre',
            },
        ),
    ]
