# Generated by Django 4.0.6 on 2023-01-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominametro', '0004_alter_prenomina_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenomina',
            name='tiempo',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
    ]
