# Generated by Django 4.0.6 on 2023-01-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominametro', '0005_alter_prenomina_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenomina',
            name='préstamo',
            field=models.CharField(default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prenomina',
            name='salario_básico_hora',
            field=models.CharField(default='-', max_length=100, null=True),
        ),
    ]
