# Generated by Django 4.0.6 on 2023-01-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominametro', '0006_alter_prenomina_préstamo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('conversor', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
                'db_table': 'conceptos',
                'order_with_respect_to': 'concepto',
            },
        ),
    ]
