# Generated by Django 4.0.6 on 2023-01-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominametro', '0007_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenomina',
            name='conversor',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
