# Generated by Django 4.0.6 on 2023-01-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominametro', '0009_concepto_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto',
            name='factor',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=6),
        ),
    ]
