# Generated by Django 4.0.6 on 2023-02-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominametro', '0011_alter_prenomina_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='concepto',
            name='tipo',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='prenomina',
            name='factor',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='prenomina',
            name='tipo',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
