# Generated by Django 4.0.6 on 2023-02-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominametro', '0012_concepto_tipo_prenomina_factor_prenomina_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad_nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.CharField(max_length=200)),
                ('novedad', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Novedad nomina',
                'verbose_name_plural': 'Novedad nomina',
                'db_table': 'novedad_nomina',
                'order_with_respect_to': 'empleado',
            },
        ),
    ]
