# Generated by Django 4.0.6 on 2023-02-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominametro', '0014_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='salario',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
