# Generated by Django 4.0.6 on 2023-02-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominametro', '0020_alter_plantilla_ausencias_no_remuneradas_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenomina',
            name='fecha_final',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='prenomina',
            name='fecha_inicial',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
