# Generated by Django 4.0.6 on 2023-03-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominametro', '0021_prenomina_fecha_final_prenomina_fecha_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mejia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Nit',
                'verbose_name_plural': 'Nit',
                'db_table': 'mejia',
            },
        ),
    ]
