# Generated by Django 4.0.6 on 2023-03-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominametro', '0022_mejia'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='nit',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
