# Generated by Django 4.0.6 on 2023-03-28 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominametro', '0023_plantilla_nit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantilla',
            name='codigo',
        ),
    ]
