# Generated by Django 4.0.6 on 2023-03-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominametro', '0024_remove_plantilla_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='incapacidad_por_accidente_laboral',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='observaciones',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='valor_pago_prestaciones',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
    ]
