# Generated by Django 4.0.6 on 2023-03-28 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominametro', '0025_plantilla_incapacidad_por_accidente_laboral_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantilla',
            name='en_1_75',
        ),
    ]
