# Generated by Django 4.0.6 on 2023-04-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominametro', '0026_remove_plantilla_en_1_75'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='en_1_75',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
    ]
