# Generated by Django 4.0.6 on 2023-04-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominametro', '0027_plantilla_en_1_75'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='concepto',
            order_with_respect_to=None,
        ),
    ]
