# Generated by Django 4.0.6 on 2023-04-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominametro', '0028_alter_concepto_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='cargo',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='plantilla',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='prenomina',
            order_with_respect_to=None,
        ),
    ]
