# Generated by Django 5.1.4 on 2025-02-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominametro', '0029_alter_cargo_order_with_respect_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenomina',
            name='conversor',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prenomina',
            name='factor',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prenomina',
            name='préstamo',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prenomina',
            name='tiempo',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='prenomina',
            name='tipo',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prenomina',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
