# Generated by Django 5.1.4 on 2025-02-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominametro', '0030_alter_prenomina_conversor_alter_prenomina_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='ausencias_no_remuneradas_hora',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='ausencias_remuneradas_hora',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='d_o_f_d_1_75',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='d_o_f_n_2_1',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='deducciones_sgss',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='deducción_retención_en_la_fuente',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='ed_1_25',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='efd_2',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='efn_2_5',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='en_1_75',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='fd_0_75',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='fn_1_1',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='horas_ordinarias',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='incapacidad_por_accidente_laboral',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='incapacidad_por_enfermedad_general_horas',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='neto_a_pagar',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='on_0_35',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='otras_deducciones',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='otros_ingresos_no_prestacionales',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='otros_ingresos_prestacionales',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='salario_mensual_basico',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='total_devengado',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='valor_hora_ordin',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='valor_pago_prestaciones',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='vr_auxilio_transporte_o_auxilio_de_conectividad',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
    ]
