# Generated by Django 5.1.4 on 2025-01-31 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
