# Generated by Django 4.0.6 on 2023-09-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perseovsfenix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matperseo',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Cantidad'),
        ),
    ]
