# Generated by Django 4.0.6 on 2023-09-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perseovsfenix', '0002_alter_matperseo_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matfenix',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='novedadperseovsfenix',
            name='cantidad_fenix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Can Fenix'),
        ),
    ]
