# Generated by Django 5.1.4 on 2025-01-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perseovsfenix', '0003_alter_matfenix_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matfenix',
            name='enperseo',
        ),
    ]
