# Generated by Django 5.1.4 on 2025-01-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perseovsfenix', '0004_remove_matfenix_enperseo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeroacta',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Acta actual'),
        ),
    ]
