# Generated by Django 5.1.4 on 2025-02-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perseovsfenix', '0005_alter_numeroacta_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matfenix',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='matperseo',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='novedadperseovsfenix',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='novedadperseovsfenix',
            name='cantidad_fenix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Can Fenix'),
        ),
        migrations.AlterField(
            model_name='novedadperseovsfenix',
            name='diferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Diferencia'),
        ),
    ]
