# Generated by Django 4.0.6 on 2022-10-07 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_oficiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inicio',
            options={'verbose_name': 'Cantidadi Inicio Oficial', 'verbose_name_plural': 'Cantidad Inicio Oficial'},
        ),
    ]
