# Generated by Django 3.2.7 on 2021-11-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pedido', models.CharField(max_length=10)),
                ('Subped', models.CharField(max_length=2)),
                ('Soli', models.CharField(max_length=2)),
                ('Producto_id', models.CharField(max_length=20)),
                ('Tipo_Trabajo', models.CharField(max_length=20)),
                ('Tipo_Elemento_ID', models.CharField(max_length=20)),
                ('Fecha_Recibo', models.DateTimeField()),
                ('Fecha_Ingreso_Sol', models.DateTimeField()),
                ('Fecha_Concepto', models.DateTimeField()),
                ('Fecha_Inicio_ANS', models.DateTimeField()),
                ('Dias_ANS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Estado', models.CharField(max_length=30)),
                ('Concepto', models.CharField(max_length=30)),
                ('Nombre_concepto', models.CharField(max_length=30)),
                ('ClienteID', models.CharField(max_length=30)),
                ('Nombre_Cliente', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=50)),
                ('Direccion_Correspondencia', models.CharField(max_length=100)),
                ('Municipio_Correspondencia', models.CharField(max_length=50)),
                ('Telefono_Contacto', models.CharField(max_length=50)),
                ('Celular_Contacto', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=100)),
                ('Municipio', models.CharField(max_length=50)),
                ('Instalacion', models.CharField(max_length=50)),
                ('Area_Operativa', models.CharField(max_length=50)),
                ('Subzona', models.CharField(max_length=50)),
                ('Area_Trabajo', models.CharField(max_length=50)),
                ('Ruta', models.CharField(max_length=50)),
                ('Coordenadax', models.CharField(max_length=50)),
                ('Coordenaday', models.CharField(max_length=50)),
                ('Actividad', models.CharField(max_length=30)),
                ('Equipo', models.CharField(max_length=50)),
                ('Nombre', models.CharField(max_length=100)),
                ('Fecha_Programación', models.DateTimeField()),
                ('Num_Proyecto', models.CharField(max_length=50)),
                ('Tipo_Direccion', models.CharField(max_length=100)),
                ('Observacion', models.CharField(max_length=100)),
                ('Observacion_Solicitud', models.CharField(max_length=100)),
                ('Pedido_CRM', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-Fecha_Concepto'],
            },
        ),
    ]
