# Generated by Django 4.2 on 2025-01-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ans',
            name='Días_ANS',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Fecha_Concepto',
            field=models.CharField(default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Fecha_Ingreso_Sol',
            field=models.CharField(default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Fecha_Inicio_ANS',
            field=models.CharField(default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Fecha_Recibo',
            field=models.CharField(default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='dias_vencimiento',
            field=models.IntegerField(default=0, null=True, verbose_name='Dias de vencimiento'),
        ),
        migrations.AlterField(
            model_name='ans',
            name='dias_vencimiento_epm',
            field=models.IntegerField(default=0, null=True, verbose_name='Dias de vencimiento epm'),
        ),
        migrations.AlterField(
            model_name='ans',
            name='estado_cierre',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='fecha_vence_epm',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='fecha_vence_sin_hora',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='fecha_vencimiento',
            field=models.CharField(default=0, max_length=30, null=True, verbose_name='Fecha vencimiento'),
        ),
        migrations.AlterField(
            model_name='ans',
            name='hora_vencimiento',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
