# Generated by Django 3.1.7 on 2021-12-14 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Encargado',
                'verbose_name_plural': 'Encargados',
            },
        ),
        migrations.AlterModelOptions(
            name='ans',
            options={'ordering': ['fecha_vencimiento'], 'verbose_name': 'Ans', 'verbose_name_plural': 'Ans'},
        ),
        migrations.RemoveField(
            model_name='ans',
            name='Dias_ANS',
        ),
        migrations.RemoveField(
            model_name='ans',
            name='Instalacion',
        ),
        migrations.RemoveField(
            model_name='ans',
            name='Observacion',
        ),
        migrations.RemoveField(
            model_name='ans',
            name='Observacion_Solicitud',
        ),
        migrations.RemoveField(
            model_name='ans',
            name='Tipo_Direccion',
        ),
        migrations.AddField(
            model_name='ans',
            name='Días_ANS',
            field=models.DecimalField(decimal_places=5, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='ans',
            name='Instalación',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='ans',
            name='Observación',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='ans',
            name='Observación_Solicitud',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='ans',
            name='Tipo_Dirección',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='ans',
            name='dias_vencimiento',
            field=models.IntegerField(default=0, verbose_name='Dias de vencimiento'),
        ),
        migrations.AddField(
            model_name='ans',
            name='encargado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ans',
            name='estado_cierre',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ans',
            name='fecha_cierre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ans',
            name='fecha_vencimiento',
            field=models.CharField(default='Sin registro', max_length=30, null=True, verbose_name='Fecha vencimiento'),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Actividad',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Area_Operativa',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Area_Trabajo',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Celular_Contacto',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='ClienteID',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Concepto',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Coordenadax',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Coordenaday',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Correo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Direccion',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Direccion_Correspondencia',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Equipo',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Estado',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Fecha_Concepto',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Fecha_Ingreso_Sol',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Fecha_Inicio_ANS',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Fecha_Programación',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Fecha_Recibo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Municipio',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Municipio_Correspondencia',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Nombre',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Nombre_Cliente',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Nombre_concepto',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Num_Proyecto',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Pedido',
            field=models.TextField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Pedido_CRM',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Producto_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Ruta',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Soli',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Subped',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Subzona',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Telefono',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Telefono_Contacto',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Tipo_Elemento_ID',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='Tipo_Trabajo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('dias_urbano', models.CharField(max_length=50, null=True)),
                ('dias_rural', models.CharField(max_length=50, null=True)),
                ('encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionvencimientos.encargado')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
