# Generated by Django 4.0.1 on 2022-05-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad_epm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('dias_urbano', models.CharField(max_length=50, null=True)),
                ('dias_rural', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Actividad epm',
                'verbose_name_plural': 'Actividades epm',
            },
        ),
    ]
