# Generated by Django 4.0.1 on 2022-05-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0002_actividad_epm'),
    ]

    operations = [
        migrations.AddField(
            model_name='ans',
            name='dias_vencimiento_epm',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Dias de vencimiento epm'),
        ),
    ]
