# Generated by Django 4.2 on 2025-01-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0002_alter_ans_días_ans_alter_ans_fecha_concepto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ans',
            name='Fecha_Programación',
            field=models.CharField(default=0, max_length=5000, null=True),
        ),
    ]
