# Generated by Django 3.1.7 on 2021-12-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0002_auto_20211214_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vencido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pedido', models.TextField(default=0, max_length=100)),
                ('Instalación', models.CharField(max_length=5000, null=True)),
                ('Actividad', models.CharField(max_length=5000, null=True)),
                ('Observación', models.CharField(max_length=5000, null=True)),
                ('fecha_vencimiento', models.CharField(default='Sin registro', max_length=30, null=True, verbose_name='Fecha vencimiento')),
                ('encargado', models.CharField(max_length=100, null=True)),
                ('fecha_cierre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Vencido',
                'verbose_name_plural': 'Vencidos',
            },
        ),
        migrations.AlterModelOptions(
            name='ans',
            options={'ordering': ['fecha_vencimiento'], 'verbose_name': 'Programador', 'verbose_name_plural': 'Programador'},
        ),
    ]
