# Generated by Django 4.0.1 on 2022-05-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0003_ans_dias_vencimiento_epm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ans',
            name='fecha_vence_epm',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
