# Generated by Django 3.1.7 on 2022-01-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0005_auto_20220103_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='ans',
            name='hora_vencimiento',
            field=models.CharField(default='Sin registro', max_length=30, null=True, verbose_name='Hora vencimiento'),
        ),
    ]
