# Generated by Django 3.1.7 on 2022-01-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0006_ans_hora_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ans',
            name='fecha_vence',
            field=models.CharField(default='Sin registro', max_length=30, null=True, verbose_name='Fecha vencimiento'),
        ),
    ]
