# Generated by Django 3.1.7 on 2022-01-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0007_ans_fecha_vence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ans',
            name='Días_ANS',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
