# Generated by Django 4.0.6 on 2022-11-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoBoniFenix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(default=0, max_length=50)),
                ('actividad', models.CharField(default=0, max_length=100)),
                ('instalador', models.CharField(default=0, max_length=200)),
                ('fecha', models.CharField(default=0, max_length=50)),
                ('codigo', models.CharField(default=0, max_length=50)),
                ('cantidad', models.CharField(default=0, max_length=50)),
                ('valor', models.CharField(default=0, max_length=50)),
                ('total', models.CharField(default=0, max_length=50)),
            ],
            options={
                'verbose_name': 'Pedido Boni Fénix',
                'verbose_name_plural': 'Pedido Boni Fénix',
            },
        ),
        migrations.CreateModel(
            name='PedidoBoniPerseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(default=0, max_length=50)),
                ('actividad', models.CharField(default=0, max_length=100)),
                ('instalador', models.CharField(default=0, max_length=200)),
                ('fecha', models.CharField(default=0, max_length=50)),
                ('codigo', models.CharField(default=0, max_length=50)),
                ('cantidad', models.CharField(default=0, max_length=50)),
                ('valor', models.CharField(default=0, max_length=50)),
                ('total', models.CharField(default=0, max_length=50)),
                ('acta', models.CharField(default=0, max_length=50)),
            ],
            options={
                'verbose_name': 'Pedido Boni Perseo',
                'verbose_name_plural': 'Pedido Boni Perseo',
            },
        ),
        migrations.CreateModel(
            name='ValorBonificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(default=0, max_length=50)),
                ('instalador', models.CharField(default=0, max_length=100)),
                ('fecha', models.CharField(default=0, max_length=100)),
                ('valor', models.CharField(default=0, max_length=50)),
                ('total_con_porcentaje', models.CharField(default=0, max_length=50)),
                ('bonificacion', models.CharField(default=0, max_length=50)),
            ],
            options={
                'verbose_name': 'Valor Bonificacion',
                'verbose_name_plural': 'Valor Bonificacion',
            },
        ),
    ]
