# Generated by Django 4.0.6 on 2022-11-23 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidobonifenix',
            options={'verbose_name': 'Fénix', 'verbose_name_plural': 'Fénix'},
        ),
        migrations.AlterModelOptions(
            name='pedidoboniperseo',
            options={'verbose_name': 'Perseo', 'verbose_name_plural': 'Perseo'},
        ),
        migrations.RenameField(
            model_name='valorbonificacion',
            old_name='total_con_porcentaje',
            new_name='valor_fenix',
        ),
        migrations.RenameField(
            model_name='valorbonificacion',
            old_name='valor',
            new_name='valor_perseo',
        ),
    ]
