# Generated by Django 4.0.6 on 2022-11-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonificaciones', '0002_alter_pedidobonifenix_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidobonifenix',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='pedidobonifenix',
            name='instalador',
        ),
    ]
