# Generated by Django 4.0.6 on 2022-11-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonificaciones', '0003_remove_pedidobonifenix_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidobonifenix',
            name='instalacion',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
