# Generated by Django 4.0.6 on 2022-11-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonificaciones', '0004_pedidobonifenix_instalacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidobonifenix',
            name='tipo',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
