# Generated by Django 4.0.6 on 2022-11-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonificaciones', '0005_pedidobonifenix_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valorbonificacion',
            old_name='bonificacion',
            new_name='diferencia',
        ),
    ]
