# Generated by Django 4.0.6 on 2022-11-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonificaciones', '0006_rename_bonificacion_valorbonificacion_diferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonificacionDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalador', models.CharField(default=0, max_length=100)),
                ('fecha', models.CharField(default=0, max_length=100)),
                ('valor', models.CharField(default=0, max_length=50)),
            ],
            options={
                'verbose_name': 'Bonificación diaria',
                'verbose_name_plural': 'Bonificaciones diarias',
            },
        ),
        migrations.AlterModelOptions(
            name='valorbonificacion',
            options={'verbose_name': 'Pedido Bonificación', 'verbose_name_plural': 'Pedido Bonificación'},
        ),
    ]
