# Generated by Django 4.0.6 on 2022-11-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonificaciones', '0007_bonificaciondia_alter_valorbonificacion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadBon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=0, max_length=100)),
            ],
            options={
                'verbose_name': 'Actividad Bon',
                'verbose_name_plural': 'Actividades Bon',
            },
        ),
        migrations.CreateModel(
            name='DatosBon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=0, max_length=100)),
                ('valor', models.CharField(default=0, max_length=100)),
            ],
            options={
                'verbose_name': 'Datos Bon',
                'verbose_name_plural': 'Datos Bon',
            },
        ),
    ]
