# Generated by Django 4.0.6 on 2022-11-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonificaciones', '0008_actividadbon_datosbon'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangoFechas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
            options={
                'verbose_name': 'Rango fechas',
                'verbose_name_plural': 'Rango fechas',
            },
        ),
    ]
