# Generated by Django 4.0.6 on 2022-11-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonificaciones', '0009_rangofechas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonificaciondia',
            old_name='valor',
            new_name='bonificacion',
        ),
        migrations.AddField(
            model_name='bonificaciondia',
            name='laborado',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
