# Generated by Django 4.0.6 on 2022-11-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonificaciones', '0010_rename_valor_bonificaciondia_bonificacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidobonifenix',
            old_name='instalacion',
            new_name='pagina',
        ),
        migrations.AddField(
            model_name='pedidobonifenix',
            name='urbrur',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
