# Generated by Django 4.0.6 on 2022-11-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonificaciones', '0012_pedidobonifenix_instalador'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidobonifenix',
            name='fecha',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
