# Generated by Django 4.0.6 on 2022-11-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonificaciones', '0013_pedidobonifenix_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromedioDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalador', models.CharField(default=0, max_length=100)),
                ('fecha', models.DateField()),
                ('valor_producido_mes', models.CharField(default=0, max_length=100)),
                ('numero_de_dias_laborados', models.CharField(default=0, max_length=100)),
                ('promedio', models.CharField(default=0, max_length=100)),
                ('bonificacion', models.CharField(default=0, max_length=100)),
            ],
            options={
                'verbose_name': 'Promedio diario',
                'verbose_name_plural': 'Promedio diario',
            },
        ),
    ]
