# Generated by Django 4.0.6 on 2022-11-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonificaciones', '0014_promediodiario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActividadBon',
        ),
        migrations.DeleteModel(
            name='DatosBon',
        ),
        migrations.DeleteModel(
            name='RangoFechas',
        ),
        migrations.DeleteModel(
            name='ValorBonificacion',
        ),
    ]
