# Generated by Django 4.0.6 on 2022-11-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonificaciones', '0015_delete_actividadbon_delete_datosbon_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BonificacionDia',
            new_name='ProducidoDia',
        ),
        migrations.RenameModel(
            old_name='PromedioDiario',
            new_name='PromedioMensual',
        ),
        migrations.AlterModelOptions(
            name='producidodia',
            options={'verbose_name': 'Producido diario', 'verbose_name_plural': 'Producido diariao'},
        ),
        migrations.AlterModelOptions(
            name='promediomensual',
            options={'verbose_name': 'Promedio mensual', 'verbose_name_plural': 'Promedio mensual'},
        ),
        migrations.RenameField(
            model_name='producidodia',
            old_name='bonificacion',
            new_name='excedente',
        ),
    ]
