# Generated by Django 4.0.6 on 2022-11-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonificaciones', '0017_rename_excedente_producidodia_producido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producidodia',
            options={'verbose_name': 'Producido diario', 'verbose_name_plural': 'Producido diario'},
        ),
    ]
