# Generated by Django 4.0.6 on 2022-11-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonificaciones', '0018_alter_producidodia_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoboniperseo',
            old_name='identificador',
            new_name='descuento_de_fenix',
        ),
    ]
