# Generated by Django 4.0.6 on 2022-11-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonificaciones', '0019_rename_identificador_pedidoboniperseo_descuento_de_fenix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoboniperseo',
            name='descuento_de_fenix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
