# Generated by Django 4.0.6 on 2022-12-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonificaciones', '0021_alter_pedidobonifenix_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='producidodia',
            name='valor_fenix',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='producidodia',
            name='valor_perseo_descuento',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
