# Generated by Django 4.0.6 on 2022-12-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonificaciones', '0022_producidodia_valor_fenix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadBonificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='--', max_length=200)),
            ],
            options={
                'verbose_name': 'Novedades',
                'verbose_name_plural': 'Novedades',
            },
        ),
    ]
