# Generated by Django 4.0.6 on 2022-12-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonificaciones', '0023_novedadbonificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedadbonificacion',
            name='pedido',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
