# Generated by Django 4.0.6 on 2022-12-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonificaciones', '0025_rename_pedidobonifenix_fenix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fenix',
            name='pagina',
        ),
    ]
