# Generated by Django 4.0.6 on 2024-01-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perseo_produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(default=0, max_length=50)),
                ('actividad', models.CharField(default=0, max_length=100)),
                ('instalador', models.CharField(default=0, max_length=200)),
                ('fecha', models.DateField()),
                ('codigo', models.CharField(default=0, max_length=50)),
                ('cantidad', models.CharField(default=0, max_length=50)),
                ('valor', models.CharField(default=0, max_length=50)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('acta', models.CharField(default=0, max_length=50)),
            ],
        ),
    ]
