# Generated by Django 4.0.6 on 2024-01-22 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novedad', models.CharField(max_length=200)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.perseo_produccion')),
            ],
            options={
                'verbose_name': 'Novedad Produccion',
                'verbose_name_plural': 'Novedades Produccion',
                'db_table': 'Novedades produccion',
            },
        ),
    ]
