# Generated by Django 4.0.6 on 2024-01-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_alter_perseo_produccion_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia_dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalador', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('mano_obra', models.DecimalField(decimal_places=3, max_digits=8)),
                ('materiales', models.DecimalField(decimal_places=3, max_digits=8)),
                ('valor_referencia', models.DecimalField(decimal_places=3, max_digits=8)),
                ('producido', models.DecimalField(decimal_places=3, max_digits=8)),
                ('treinta_porciento', models.DecimalField(decimal_places=3, max_digits=8)),
                ('por_persona', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
            options={
                'verbose_name': 'Produccion dia dia',
                'verbose_name_plural': 'Produccion dia dia',
                'db_table': 'Produccion dia dia',
            },
        ),
        migrations.CreateModel(
            name='Valor_referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Valor referencia',
                'verbose_name_plural': 'Valor referencia',
            },
        ),
        migrations.AlterModelOptions(
            name='novedadproduccion',
            options={'verbose_name': 'Produccion novedades', 'verbose_name_plural': 'Produccion novedades'},
        ),
        migrations.AlterModelOptions(
            name='perseo_produccion',
            options={'verbose_name': 'Produccion Perseo', 'verbose_name_plural': 'Produccion Perseo'},
        ),
        migrations.AlterModelTable(
            name='novedadproduccion',
            table='Produccion novedades',
        ),
        migrations.AlterModelTable(
            name='perseo_produccion',
            table='Produccion Perseo',
        ),
    ]
