# Generated by Django 4.0.6 on 2024-01-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_dia_dia_valor_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perseo_produccion',
            name='total',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='perseo_produccion',
            name='valor',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
