# Generated by Django 4.0.6 on 2024-01-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0010_alter_dia_dia_mano_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia_dia',
            name='materiales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='dia_dia',
            name='por_persona',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='dia_dia',
            name='producido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='dia_dia',
            name='treinta_porciento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='dia_dia',
            name='valor_referencia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='perseo_produccion',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='perseo_produccion',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='valor_referencia',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
