# Generated by Django 4.0.6 on 2024-10-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=255)),
                ('actividad', models.CharField(max_length=255)),
                ('instalador', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('acta', models.CharField(max_length=255)),
            ],
        ),
    ]
