# Generated by Django 4.0.6 on 2024-10-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_mejia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSeleccionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('guia', models.CharField(max_length=255)),
            ],
        ),
    ]
