# Generated by Django 4.0.6 on 2024-10-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_mejia', '0002_materialseleccionado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=255)),
                ('actividad', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
