# Generated by Django 4.0.6 on 2024-10-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_mejia', '0004_alter_actab_cantidad_alter_pedido_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparacionPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=255)),
                ('suma_material_pedido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('suma_material_acta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('actividad', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('instalador', models.CharField(max_length=255)),
            ],
        ),
    ]
