# Generated by Django 4.0.6 on 2024-10-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_mejia', '0006_comparacionpedido_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparacionpedido',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
