# Generated by Django 4.0.6 on 2024-10-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_mejia', '0007_alter_comparacionpedido_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='guia',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
