# Generated by Django 5.1.4 on 2025-02-18 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(default=0, max_length=100, null=True)),
                ('area_operativa', models.CharField(default=0, max_length=100, null=True)),
                ('subz', models.CharField(default=0, max_length=100, null=True)),
                ('ruta', models.CharField(default=0, max_length=100, null=True)),
                ('municipio', models.CharField(default=0, max_length=100, null=True)),
                ('contrato', models.CharField(default=0, max_length=100, null=True)),
                ('acta', models.CharField(default=0, max_length=100, null=True)),
                ('actividad', models.CharField(default=0, max_length=100, null=True)),
                ('fecha_estado', models.CharField(default=0, max_length=100, null=True)),
                ('pagina', models.CharField(default=0, max_length=100, null=True)),
                ('urbrur', models.CharField(default=0, max_length=100, null=True)),
                ('tipre', models.CharField(default=0, max_length=100, null=True)),
                ('red_interna', models.CharField(default=0, max_length=100, null=True)),
                ('tipo_operacion', models.CharField(default=0, max_length=100, null=True)),
                ('descent', models.CharField(default=0, max_length=100, null=True)),
                ('tipo', models.CharField(default=0, max_length=100, null=True)),
                ('cobro', models.CharField(default=0, max_length=100, null=True)),
                ('suminis', models.CharField(default='0', max_length=100, null=True)),
                ('item_cont', models.CharField(default='0', max_length=100, null=True)),
                ('item_res', models.CharField(default=0, max_length=100, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('vlr_cliente', models.CharField(default=0, max_length=100, null=True)),
                ('valor_costo', models.CharField(default=0, max_length=100, null=True)),
                ('tipo_item', models.CharField(default=0, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Acta',
                'verbose_name_plural': 'Acta',
                'ordering': ['actividad'],
            },
        ),
        migrations.CreateModel(
            name='ActividadLegalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Actividades legalización',
                'verbose_name_plural': 'Actividades legalización',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CantidadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, verbose_name='Item cobro')),
                ('cantidad_cobro', models.IntegerField()),
                ('tipo_restriccion', models.CharField(choices=[('EXACTO', 'Exacto'), ('MAXIMO', 'Máximo')], default='EXACTO', max_length=10)),
                ('max_cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cantidades Items',
                'verbose_name_plural': 'Cantidades Items',
            },
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(default=0, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Materiales',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='Novedad_acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(default=0, max_length=200, null=True)),
                ('actividad', models.CharField(default=0, max_length=200, null=True)),
                ('municipio', models.CharField(default=0, max_length=200, null=True)),
                ('pagina', models.CharField(default=0, max_length=200, null=True)),
                ('item', models.CharField(default=0, max_length=200, null=True)),
                ('novedad', models.CharField(default=0, max_length=200, null=True)),
                ('estado', models.CharField(default='Aplica', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Novedades Acta',
                'verbose_name_plural': 'Novedades Acta',
                'ordering': ['actividad'],
            },
        ),
        migrations.CreateModel(
            name='VariableAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=200, null=True)),
                ('contrato', models.CharField(max_length=200, null=True)),
                ('codigo_sellos', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Variables contrato',
                'verbose_name_plural': 'Variables contrato',
                'ordering': ['region'],
            },
        ),
        migrations.CreateModel(
            name='RelacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_relacion', models.CharField(max_length=30)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_acta.acta')),
            ],
        ),
    ]
