# Generated by Django 5.1.2 on 2025-04-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_acta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad_acta',
            name='fecha',
            field=models.CharField(default='Sin fecha', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='novedad_acta',
            unique_together={('pedido', 'novedad')},
        ),
    ]
