# Generated by Django 4.0.6 on 2023-03-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_acta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(default=0, max_length=100)),
            ],
            options={
                'verbose_name': 'Materiales',
                'verbose_name_plural': 'Materiales',
            },
        ),
    ]
