# Generated by Django 5.1.4 on 2025-01-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_acta', '0002_alter_materiales_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad_acta',
            name='tipre',
        ),
    ]
