# Generated by Django 4.0.6 on 2023-03-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_acta', '0002_materiales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='item_cont',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='acta',
            name='suminis',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
