# Generated by Django 5.1.4 on 2025-02-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_acta', '0003_remove_novedad_acta_tipre'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default=0, max_length=200, null=True)),
            ],
        ),
    ]
