# Generated by Django 5.1.4 on 2025-02-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_acta', '0004_variableanalisis'),
    ]

    operations = [
        migrations.AddField(
            model_name='variableanalisis',
            name='contrato',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
    ]
