# Generated by Django 4.0.6 on 2023-04-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_acta', '0004_alter_acta_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
    ]
