# Generated by Django 5.1.4 on 2025-02-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_acta', '0005_variableanalisis_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variableanalisis',
            name='contrato',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variableanalisis',
            name='region',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
