# Generated by Django 5.1.4 on 2025-02-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_acta', '0006_alter_variableanalisis_contrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadLegalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Actividades legalización',
                'verbose_name_plural': 'Actividades legalización',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='variableanalisis',
            options={'ordering': ['region'], 'verbose_name': 'Variables contrato', 'verbose_name_plural': 'Variables contrato'},
        ),
    ]
