# Generated by Django 5.1.4 on 2025-02-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_acta', '0007_actividadlegalizacion_alter_variableanalisis_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='variableanalisis',
            name='codigo_sellos',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
