# Generated by Django 5.1.4 on 2025-02-17 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_acta', '0008_variableanalisis_codigo_sellos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CantidadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cobro', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_acta.acta')),
            ],
            options={
                'verbose_name': 'Cantidades Items',
                'verbose_name_plural': 'Cantidades Items',
            },
        ),
        migrations.CreateModel(
            name='RelacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_relacion', models.CharField(max_length=30)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_acta.acta')),
            ],
        ),
    ]
