# Generated by Django 5.1.4 on 2025-02-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_acta', '0009_cantidaditem_relacionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantidaditem',
            name='item',
            field=models.CharField(max_length=50, verbose_name='Item cobro'),
        ),
    ]
