# Generated by Django 5.1.4 on 2025-02-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_acta', '0010_alter_cantidaditem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantidaditem',
            name='max_cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cantidaditem',
            name='min_cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cantidaditem',
            name='tipo_restriccion',
            field=models.CharField(choices=[('EXACTO', 'Exacto'), ('MAXIMO', 'Máximo'), ('RANGO', 'Rango')], default='EXACTO', max_length=10),
        ),
    ]
