# Generated by Django 5.1.4 on 2025-02-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_acta', '0011_cantidaditem_max_cantidad_cantidaditem_min_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cantidaditem',
            name='min_cantidad',
        ),
        migrations.AlterField(
            model_name='cantidaditem',
            name='tipo_restriccion',
            field=models.CharField(choices=[('EXACTO', 'Exacto'), ('MAXIMO', 'Máximo')], default='EXACTO', max_length=10),
        ),
    ]
