# Generated by Django 4.0.6 on 2022-10-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoMedidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(default=0, max_length=100, null=True)),
                ('municipio', models.CharField(default=0, max_length=100, null=True)),
                ('actividad', models.CharField(default=0, max_length=100, null=True)),
                ('pagina', models.CharField(default=0, max_length=100, null=True)),
                ('suminis', models.CharField(default=0, max_length=100, null=True)),
                ('item_cont', models.CharField(default=0, max_length=100, null=True)),
                ('cantidad', models.CharField(default=0, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Acta Medidores',
                'verbose_name_plural': 'Acta Medidoress',
            },
        ),
        migrations.DeleteModel(
            name='ActaMedidores',
        ),
    ]
