# Generated by Django 4.0.6 on 2022-10-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medidores', '0002_pedidomedidores_delete_actamedidores'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadMedidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medidores.pedidomedidores')),
            ],
            options={
                'verbose_name': 'Novedades Medidores',
                'verbose_name_plural': 'Novedades Medidoress',
            },
        ),
    ]
