# Generated by Django 4.0.6 on 2022-10-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidores', '0003_novedadmedidores'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedadmedidores',
            name='novedad',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
    ]
