# Generated by Django 5.1.4 on 2025-05-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaItemActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('item_cont', models.CharField(help_text='Código de actividad (campo item_cont)', max_length=50)),
                ('suminis_requerido', models.CharField(help_text='Código de suministro requerido (campo suminis)', max_length=50)),
                ('comparador', models.CharField(choices=[('==', 'Igual a'), ('>=', 'Mayor o igual a'), ('>', 'Mayor que'), ('<=', 'Menor o igual a'), ('<', 'Menor que'), ('!=', 'Diferente de')], default='==', max_length=2)),
                ('cantidad', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ReglaSuministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('suminis_origen', models.CharField(help_text='Suministro que activa la regla', max_length=50)),
                ('requiere_suminis', models.CharField(blank=True, help_text='Otro suministro que se requiere', max_length=50, null=True)),
                ('requiere_item_cont', models.CharField(blank=True, help_text='O una actividad (item_cont) que se requiere', max_length=50, null=True)),
                ('comparador', models.CharField(choices=[('==', 'Igual a'), ('>=', 'Mayor o igual a'), ('>', 'Mayor que'), ('<=', 'Menor o igual a'), ('<', 'Menor que'), ('!=', 'Diferente de')], default='==', max_length=2)),
                ('cantidad', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
