# Generated by Django 5.1.4 on 2025-05-27 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRegla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('suministro', 'Suministro'), ('actividad', 'Actividad')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RelacionItemRegla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparador', models.CharField(choices=[('igual_a', 'Igual a'), ('mayor_igual_a', 'Mayor o igual a'), ('mayor_que', 'Mayor que'), ('menor_igual_que', 'Menor o igual a'), ('menor_que', 'Menor que'), ('diferente_de', 'Diferente de')], max_length=30)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones', to='nuevo_analisis.itemregla')),
                ('item_requerido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='es_requerido_por', to='nuevo_analisis.itemregla')),
            ],
        ),
        migrations.DeleteModel(
            name='ReglaItemActividad',
        ),
        migrations.DeleteModel(
            name='ReglaSuministro',
        ),
    ]
