# Generated by Django 5.1.4 on 2025-05-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0002_itemregla_relacionitemregla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacionitemregla',
            name='factor',
            field=models.CharField(choices=[('unico', 'Unico'), ('Multiple', 'Multiple')], default='unico', max_length=30),
        ),
    ]
