# Generated by Django 5.1.4 on 2025-05-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0004_relacionitemregla_tipo_requerido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionitemregla',
            name='item_requerido',
            field=models.CharField(choices=[('suministro', 'Suministro'), ('actividad', 'Actividad')], max_length=30),
        ),
    ]
