# Generated by Django 5.1.4 on 2025-05-28 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0005_alter_relacionitemregla_item_requerido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionitemregla',
            name='item_requerido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='es_requerido_por', to='nuevo_analisis.itemregla'),
        ),
        migrations.AlterField(
            model_name='relacionitemregla',
            name='tipo_requerido',
            field=models.CharField(choices=[('suministro', 'Suministro'), ('actividad', 'Actividad')], default='suministro', max_length=30),
        ),
    ]
