# Generated by Django 5.1.4 on 2025-05-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0006_alter_relacionitemregla_item_requerido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacionitemregla',
            name='cantidad_requeridad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='relacionitemregla',
            name='requiere_cantidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='relacionitemregla',
            name='comparador',
            field=models.CharField(choices=[('igual_a', 'Igual a'), ('mayor_igual_a', 'Mayor o igual a'), ('mayor_que', 'Mayor que'), ('menor_igual_a', 'Menor o igual a'), ('menor_que', 'Menor que'), ('diferente_de', 'Diferente de')], max_length=30),
        ),
        migrations.AlterField(
            model_name='relacionitemregla',
            name='factor',
            field=models.CharField(choices=[('unico', 'Unico'), ('multiple', 'Multiple')], default='unico', max_length=30),
        ),
    ]
