# Generated by Django 5.1.4 on 2025-05-29 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0007_relacionitemregla_cantidad_requeridad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relacionitemregla',
            old_name='cantidad_requeridad',
            new_name='cantidad_requerida',
        ),
    ]
