# Generated by Django 5.1.4 on 2025-06-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0008_rename_cantidad_requeridad_relacionitemregla_cantidad_requerida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relacionitemregla',
            old_name='item_requerido',
            new_name='Item_busqueda',
        ),
        migrations.RenameField(
            model_name='relacionitemregla',
            old_name='cantidad_requerida',
            new_name='cantidad_condicion',
        ),
        migrations.RenameField(
            model_name='relacionitemregla',
            old_name='item',
            new_name='objeto',
        ),
        migrations.RemoveField(
            model_name='relacionitemregla',
            name='tipo_requerido',
        ),
        migrations.AlterField(
            model_name='relacionitemregla',
            name='comparador',
            field=models.CharField(choices=[('igual_a', 'Igual a'), ('mayor_a', 'Mayor a'), ('menor_a', 'Menor a')], max_length=30),
        ),
        migrations.AlterField(
            model_name='relacionitemregla',
            name='factor',
            field=models.CharField(choices=[('unico', 'Unico'), ('multiple', 'Multiple')], max_length=30),
        ),
    ]
