# Generated by Django 5.1.4 on 2025-06-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0009_rename_item_requerido_relacionitemregla_item_busqueda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionitemregla',
            name='Item_busqueda',
            field=models.CharField(max_length=30),
        ),
    ]
