# Generated by Django 5.1.4 on 2025-06-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0010_alter_relacionitemregla_item_busqueda'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacionitemregla',
            name='conjuncion',
            field=models.CharField(choices=[('todos', 'Todos'), ('uno', 'Uno')], default='todos', max_length=30),
        ),
    ]
