# Generated by Django 5.1.4 on 2025-06-11 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0011_relacionitemregla_conjuncion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemregla',
            options={'verbose_name': 'Ítem de Regla', 'verbose_name_plural': 'Ítems de Regla'},
        ),
        migrations.AlterModelOptions(
            name='relacionitemregla',
            options={'verbose_name': 'Relación de Ítem de Regla', 'verbose_name_plural': 'Relaciones de Ítems de Regla'},
        ),
        migrations.AddField(
            model_name='relacionitemregla',
            name='tipo_item_busqueda',
            field=models.CharField(choices=[('suministro', 'Suministro'), ('actividad', 'Actividad'), ('obra', 'Obra')], default='suministro', max_length=30, verbose_name='Tipo Item busqueda'),
        ),
        migrations.AlterField(
            model_name='relacionitemregla',
            name='Item_busqueda',
            field=models.CharField(max_length=255, verbose_name='Ítem(s) de Búsqueda'),
        ),
        migrations.AlterField(
            model_name='relacionitemregla',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad Requerida'),
        ),
        migrations.AlterField(
            model_name='relacionitemregla',
            name='cantidad_condicion',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad Condición'),
        ),
        migrations.AlterField(
            model_name='relacionitemregla',
            name='comparador',
            field=models.CharField(choices=[('igual_a', 'Igual a'), ('mayor_a', 'Mayor a'), ('menor_a', 'Menor a')], max_length=30, verbose_name='Comparador'),
        ),
        migrations.AlterField(
            model_name='relacionitemregla',
            name='conjuncion',
            field=models.CharField(choices=[('todos', 'Todos'), ('uno', 'Uno')], default='todos', max_length=30, verbose_name='Condición Lógica'),
        ),
        migrations.AlterField(
            model_name='relacionitemregla',
            name='factor',
            field=models.CharField(choices=[('unico', 'Unico'), ('multiple', 'Multiple')], max_length=30, verbose_name='Factor de Búsqueda'),
        ),
        migrations.AlterField(
            model_name='relacionitemregla',
            name='objeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones', to='nuevo_analisis.itemregla', verbose_name='Objeto Principal'),
        ),
        migrations.AlterField(
            model_name='relacionitemregla',
            name='requiere_cantidad',
            field=models.BooleanField(default=False, verbose_name='¿Requiere Cantidad?'),
        ),
    ]
