# Generated by Django 4.2 on 2025-06-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0012_alter_itemregla_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relacionitemregla',
            old_name='Item_busqueda',
            new_name='item_busqueda',
        ),
        migrations.AlterField(
            model_name='itemregla',
            name='tipo',
            field=models.CharField(choices=[('suminis', 'Suministro'), ('actividad', 'Actividad'), ('item_cont', 'Obra')], max_length=30),
        ),
        migrations.AlterField(
            model_name='relacionitemregla',
            name='tipo_item_busqueda',
            field=models.CharField(choices=[('suminis', 'Suministro'), ('actividad', 'Actividad'), ('item_cont', 'Obra')], default='suministro', max_length=30, verbose_name='Tipo Item busqueda'),
        ),
    ]
