# Generated by Django 4.2 on 2025-06-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0013_rename_item_busqueda_relacionitemregla_item_busqueda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacionitemregla',
            name='verificar_todos_los_items',
            field=models.BooleanField(default=True),
        ),
    ]
