# Generated by Django 4.2 on 2025-06-15 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0015_rename_verificar_todos_los_items_relacionitemregla_verificar_cantidad_en_todos_los_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relacionitemregla',
            old_name='verificar_cantidad_en_todos_los_items',
            new_name='verificar_todos_los_items',
        ),
    ]
