# Generated by Django 5.1.4 on 2025-06-16 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0017_rename_verificar_todos_los_items_relacionitemregla_verificar_cantidad_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionIncompatibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_incompatibilidad', models.CharField(max_length=255, verbose_name='Ítem(s) de incompatibilidad')),
                ('tipo_item_incompatibilidad', models.CharField(choices=[('suminis', 'Suministro'), ('actividad', 'Actividad'), ('item_cont', 'Obra')], max_length=30, verbose_name='Tipo Item incompatibilidad')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacion_incompatible', to='nuevo_analisis.itemregla', verbose_name='Objeto Principal')),
            ],
            options={
                'verbose_name': 'Relación de Ítem de Regla',
                'verbose_name_plural': 'Relaciones de Ítems de Regla',
            },
        ),
    ]
