# Generated by Django 5.1.4 on 2025-06-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0018_relacionincompatibilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacionincompatibilidad',
            name='cantidad',
        ),
    ]
