# Generated by Django 5.1.4 on 2025-06-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0019_remove_relacionincompatibilidad_cantidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relacionincompatibilidad',
            options={'verbose_name': 'Relación de incompatibilidad', 'verbose_name_plural': 'Relaciones de incompatibilidad de Regla'},
        ),
    ]
