# Generated by Django 4.2 on 2025-06-17 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0021_alter_relacionincompatibilidad_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionUltimoCaracter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplica', models.BooleanField(default=True)),
                ('item_caracter', models.CharField(max_length=255, verbose_name='Ítems caracter')),
                ('tipo_item_incompatibilidad', models.CharField(choices=[('suminis', 'Suministro'), ('actividad', 'Actividad'), ('item_cont', 'Obra')], max_length=30, verbose_name='Tipo Item incompatibilidad')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacion_caracter', to='nuevo_analisis.itemregla', verbose_name='Objeto Principal')),
            ],
            options={
                'verbose_name': 'Relación caracter',
                'verbose_name_plural': 'Relaciones caracteres',
            },
        ),
    ]
