# Generated by Django 4.2 on 2025-06-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0022_relacionultimocaracter'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacionultimocaracter',
            name='caracter',
            field=models.CharField(default='A', max_length=5),
        ),
    ]
