# Generated by Django 4.2 on 2025-06-17 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0023_relacionultimocaracter_caracter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relacionultimocaracter',
            old_name='tipo_item_incompatibilidad',
            new_name='tipo_item',
        ),
    ]
