# Generated by Django 5.1.4 on 2025-06-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0024_rename_tipo_item_incompatibilidad_relacionultimocaracter_tipo_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacionultimocaracter',
            name='todos_los_registros',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='relacionultimocaracter',
            name='tipo_item',
            field=models.CharField(choices=[('suminis', 'Suministro'), ('actividad', 'Actividad'), ('item_cont', 'Obra')], max_length=30, verbose_name='Tipo Item'),
        ),
    ]
