# Generated by Django 5.1.4 on 2025-06-17 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0026_alter_relacionultimocaracter_item_caracter'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionLimiteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('suminis', 'Suministro'), ('actividad', 'Actividad'), ('item_cont', 'Obra')], max_length=30, verbose_name='Tipo Item cantidad')),
                ('items', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ítems cantidad')),
                ('cantidad', models.IntegerField()),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacion_cantidad', to='nuevo_analisis.itemregla', verbose_name='Objeto Principal')),
            ],
            options={
                'verbose_name': 'Relación cantidad',
                'verbose_name_plural': 'Relaciones cantidades',
            },
        ),
    ]
