# Generated by Django 5.1.4 on 2025-06-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0027_relacionlimiteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacionlimiteitem',
            name='comparador',
            field=models.CharField(choices=[('igual_a', 'Igual a'), ('mayor_a', 'Mayor a'), ('menor_a', 'Menor a')], default='actividad', max_length=30, verbose_name='Comparador Item cantidad'),
        ),
    ]
