# Generated by Django 5.1.4 on 2025-06-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0028_relacionlimiteitem_comparador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacionlimiteitem',
            name='objeto',
        ),
    ]
