# Generated by Django 5.1.4 on 2025-06-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0029_remove_relacionlimiteitem_objeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionlimiteitem',
            name='comparador',
            field=models.CharField(choices=[('igual_a', 'Igual a'), ('mayor_a', 'Mayor a'), ('menor_a', 'Menor a')], default='igual_a', max_length=30, verbose_name='Comparador Item cantidad'),
        ),
        migrations.AlterField(
            model_name='relacionlimiteitem',
            name='tipo_item',
            field=models.CharField(choices=[('suminis', 'Suministro'), ('item_cont', 'Obra')], max_length=30, verbose_name='Tipo Item cantidad'),
        ),
    ]
