# Generated by Django 5.1.4 on 2025-06-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0030_alter_relacionlimiteitem_comparador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacionultimocaracter',
            name='es_actividad',
            field=models.BooleanField(default=True),
        ),
    ]
