# Generated by Django 5.1.4 on 2025-06-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_analisis', '0031_relacionultimocaracter_es_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacionultimocaracter',
            name='es_actividad',
        ),
    ]
